### ISSUE TITLE
Error at deleting additional price and choosing "Sem adicional"

### ISSUE THREAD

**Issue by matheusgnreis** [ecomclub/ecomplus-admin#14]
When i set like 15% with additional price and then i delete the price and choose "Sem adicional", E-Com Plus display: [data.add_to_price deve ter a propriedade requerida addition]

**Comment by leomp12** [comment]
Solved with https://github.com/ecomclub/ecomplus-admin/commit/cd163bb04ecd4924dd14f87fe6b119abfced0c25
Please test and close the issue
