### ISSUE TITLE
Swaping orders/products/ in edition page

### ISSUE THREAD

**Issue by vitorrgg** [ecomclub/ecomplus-admin#17]
Adding arrows ou with a hotkey

**Comment by leomp12** [comment]
Done with https://github.com/ecomclub/ecomplus-admin/commit/5a6bab757161e9a3cac281c6902bbbd5f40515ac and https://github.com/ecomclub/ecomplus-admin/commit/965c8d248f3f59eb82c5a7e42a5f6aafcbc79099
:+1:

**Comment by leomp12** [comment]
Working with arrows and shortcut `j` and `k`

**Comment by vitorrgg** [comment]
Arrows are not shown when opening products in a new tab

**Comment by leomp12** [comment]
Yup, each tab has his own routes history, so it's not a bug
