### ISSUE TITLE
Links na página de produto

### ISSUE THREAD

**Issue by vitorrgg** [ecomclub/ecomplus-admin#75]
Esses links na página de produto não estão #pegando a url da loja. 
![image](https://user-images.githubusercontent.com/35348281/72900072-ff905000-3d05-11ea-9954-388917fade1c.png)

**Comment by leomp12** [comment]
@matheusgnreis chegou a trabalhar nisto pegando o domain salvo em `stores/me.json`?

**Comment by matheusgnreis** [comment]
Já, tinha avisado o Rocha no dia que fiz, não sabia que ele havia aberto issue

**Comment by leomp12** [comment]
Boa!
