### ISSUE TITLE
Adicionar categoria em massa [Listagem de Produtos]

### ISSUE THREAD

**Issue by eduvlemes** [ecomclub/ecomplus-admin#80]
Ao adicionar categorias em massa, o flash de "Categoria Inserida com sucesso" é repetido para cada categoria x quantidade de produtos. Se possível, juntar tudo em uma requisição e exibir dois flash, um de "Aguarde" e outro de "Finalizado"

**Comment by leomp12** [comment]
@igorsfreitas pode dar uma olhada nisso pra mim por favor?
Só um chute, mas provavelmente está aparecendo algum modal/toast a cada request, deveríamos emitir a notificação apenas depois da última operação neste caso, talvez exibir um spinner em quando isto...

> Acho que mexendo nisto você vai poder opinar melhor o caminho pra próxima major, e então conversamos sobre.

**Comment by matheusgnreis** [comment]
@eduvlemes depois dá uma olhada lá, subi uma versão no https://app-dev.e-com.plus/ se todos acharem que satisfez, eu subo para o branch de produção
