### ISSUE TITLE
Problema com criação de variações tanto no app.e-com.plus, quanto no current

### ISSUE THREAD

**Issue by matheusgnreis** [ecomclub/ecomplus-admin#9]
Para criar variações, eu insiro o nome da grade, o valor e clico no +, mas nada ocorre, o que foi escrito fica como placeholder para quando for escrever outra opção. Quando tento inserir Cores, não aparece em nenhum momento o quadrado com os exemplos de cores para seleção. Isso tudo ocorre somente no safari

**Comment by leomp12** [comment]
Qual é a versão do safari? @matheusgnreis

**Comment by leomp12** [comment]
Testar sempre na última versão em https://app-current.e-com.plus/pages/login.html

**Comment by matheusgnreis** [comment]
Versão 12 é a última versão do meu sistemaAtt, Matheus GuedesCo-Fundador da E-Com ClubSkype: matheusgnreis www.e-com.club---- On Seg, 08 out 2018 23:56:09 -0300  Leonardo Matos<notifications@github.com> wrote ----Testar sempre na última versão em https://app-current.e-com.plus/pages/login.html  —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by leomp12** [comment]
Fiz um commit para debugar, testa de novo por favor e me envia o que tiver no log do console

**Comment by matheusgnreis** [comment]
Att, Matheus Guedes Co-Fundador da E-Com Club Skype: matheusgnreis www.e-com.club ---- On Mon, 08 Oct 2018 23:59:51 -0300 Leonardo Matos <notifications@github.com> wrote ---- Fiz um commit para debugar, testa de novo por favor e me envia o que tiver no log do console — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by matheusgnreis** [comment]
Ou, quando eu clico no autocomplete. Tipo, digito Ta e clico para completar para Tamanho e insiro o P e depois em +, não funciona. Mas se eu digito Tamanho e depois coloco P, funciona. Mesma coisa para cor, se eu digitar Cor primária, consigo inserir a cor. Agora, se digito apenas C e dai clico no autocomplete, não consigo inserir mais nada. Att, Matheus Guedes Co-Fundador da E-Com Club Skype: matheusgnreis www.e-com.club ---- On Mon, 08 Oct 2018 23:59:51 -0300 Leonardo Matos <notifications@github.com> wrote ---- Fiz um commit para debugar, testa de novo por favor e me envia o que tiver no log do console — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by leomp12** [comment]
Estava funcionando antes? Tenta de novo por favor...
